# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/kdbusaddons': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/kemoticons': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/khtml': '@stable'
    'frameworks/knotifyconfig': '@stable'
    'frameworks/kparts': '@stable'
    'frameworks/ktexteditor': '@stable'
    'frameworks/kwallet': '@stable'
    'frameworks/kdelibs4support': '@stable'
    'frameworks/kcontacts': '@stable'
    'frameworks/kcmutils': '@stable'
    'frameworks/kdnssd': '@stable'
    'libraries/phonon': '@stable'
    'pim/kidentitymanagement': '@stable'
    'pim/libkleo': '@stable'
